# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-15 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_det',
        ),
    ]
